// ignore_for_file: non_constant_identifier_names

class MovieDetailModel {
  final String adult,
      backdrop_path,
      belongs_to_collection,
      budget,
      genres,
      homepage,
      id,
      imdb_id,
      original_language,
      original_title,
      overview,
      popularity,
      poster_path,
      production_companies,
      production_countries,
      release_date,
      revenue,
      runtime,
      spoken_languages,
      status,
      tagline,
      title,
      video,
      vote_average,
      vote_count;

  MovieDetailModel.fromJson(Map<String, dynamic> json)
      : adult = json['adult'],
        backdrop_path = json['backdrop_path'],
        belongs_to_collection = json['belongs_to_collection'],
        budget = json['budget'],
        genres = json['genres'],
        homepage = json['homepage'],
        id = json['id'],
        imdb_id = json['imdb_id'],
        original_language = json['original_language'],
        original_title = json['original_title'],
        overview = json['overview'],
        popularity = json['popularity'],
        poster_path = json['poster_path'],
        production_companies = json['production_companies'],
        production_countries = json['production_countries'],
        release_date = json['release_date'],
        revenue = json['revenue'],
        runtime = json['runtime'],
        spoken_languages = json['spoken_languages'],
        status = json['status'],
        tagline = json['tagline'],
        title = json['title'],
        video = json['video'],
        vote_average = json['vote_average'],
        vote_count = json['vote_count'];
}
